SystemGroup lpadmin
User lp
Group lp
AccessLog /var/log/cups/access_log
ErrorLog /var/log/cups/error_log
PageLog /var/log/cups/page_log
TempDir /var/spool/cups/tmp
RequestRoot /var/spool/cups
ServerRoot /etc/cups
StateDir /run/cups

